# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "azik-k@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "vasli"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80